# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
  - master

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Initialization
    displayName: Initialization
    jobs:
      - job: Initialization
        displayName: Initialization
        steps:
          - task: SonarQubePrepare@5
            continueOnError: true
            inputs:
              scannerMode: 'Other'
  - stage: Build
    displayName: Build
    jobs:
      - job: Build
        displayName: Build
        steps:
          - task: Maven@3
            displayName: Maven build
            inputs:
              mavenPomFile: 'pom.xml'
              mavenOptions: '-Xmx3072m'
              javaHomeOption: 'JDKVersion'
              jdkVersionOption: '1.8'
              jdkArchitectureOption: 'x64'
              publishJUnitResults: true
              testResultsFiles: '**/surefire-reports/TEST-*.xml'
              goals: 'package'
          - task: SonarQubeAnalyze@5
            displayName: SonarQube
            continueOnError: true
          - task: Docker@2
            displayName: Docker build of config-service
            inputs:
              containerRegistry: 'Docker Hub'
              repository: 'suchen2008/spring-microservices-organization-config'
              command: 'buildAndPush'
              Dockerfile: 'config-service/Dockerfile'
  - stage: Deploy
    displayName: Deploy
    jobs:
      - job: Deploy
        displayName: Deploy
        steps:
          - task: CmdLine@2
            inputs:
              script: 'echo deploying'