version: 2.1

jobs:
  build:
    docker:
      - image: 'cimg/openjdk:17.0.0'
    steps:
      - checkout
      - run:
          name: Analyze on SonarCloud
          command: mvn verify sonar:sonar

executors:
  j17:
    docker:
      - image: 'cimg/openjdk:17.0'

orbs:
  maven: circleci/maven@1.2.0

workflows:
  maven_test:
    jobs:
      - maven/test:
          executor: j17
      - build:
          context: SonarCloud
