version: 2.1

jobs:
  build:
    docker:
      - image: 'cimg/openjdk:21.0.5'
    steps:
      - checkout
      - run:
          name: Analyze on SonarCloud
          command: mvn verify sonar:sonar

executors:
  jdk:
    docker:
      - image: 'cimg/openjdk:21.0.5'

orbs:
  maven: circleci/maven@2.0.0

workflows:
  maven_test:
    jobs:
      - maven/test:
          executor: jdk
      - build:
          context: SonarCloud
