version: 2.1

jobs:
  analyze:
    docker:
      - image: 'cimg/openjdk:25.0'
    steps:
      - checkout
      - git-shallow-clone/checkout_advanced:
          clone_options: '--filter=blob:none'
      - run:
          name: "Git fetch"
          command: git fetch --no-filter --refetch
      - run:
          name: Analyze on SonarCloud
          command: mvn verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar
  build-image:
    executor: vm
    steps:
      - checkout
      - run:
          name: Install OpenJDK 25
          command: |
            java -version
            sudo apt-get update && sudo apt-get install openjdk-25-jdk
            sudo update-alternatives --set java /usr/lib/jvm/java-25-openjdk-amd64/bin/java
            sudo update-alternatives --set javac /usr/lib/jvm/java-25-openjdk-amd64/bin/javac
            java -version
            export JAVA_HOME=/usr/lib/jvm/java-25-openjdk-amd64
      - run:
          name: Build Image
          command: |
            mvn clean package -Pbuild-image -DskipTests

executors:
  jdk:
    docker:
      - image: 'cimg/openjdk:25.0'
  vm:
    machine:
      image: ubuntu-2204:current
    environment:
      architecture: "amd64"
      platform: "linux/amd64"

orbs:
  maven: circleci/maven@2.1.1
  git-shallow-clone: guitarrapc/git-shallow-clone@2.8.0

workflows:
  maven_test:
    jobs:
      - maven/test:
          executor: jdk
      - analyze:
          context: SonarCloud
      - build-image
