version: 2.1

jobs:
  analyze:
    docker:
      - image: 'cimg/openjdk:25.0'
    steps:
      - checkout
      - run:
          name: Analyze on SonarCloud
          command: mvn verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar

executors:
  jdk:
    docker:
      - image: 'cimg/openjdk:25.0'

orbs:
  maven: circleci/maven@2.1.1

workflows:
  maven_test:
    jobs:
      - maven/test:
          executor: jdk
      - analyze:
          context: SonarCloud
